changesetBaseRefs:
- "master"
- "origin/master"
- "upstream/master"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-rescript.cjs
    spec: bundles/@yarnpkg/plugin-rescript.js

yarnPath: .yarn/releases/yarn-berry.cjs
